from flask import Flask, render_template, request, redirect, url_for, session, flash, send_file, g, make_response
from werkzeug.security import generate_password_hash, check_password_hash
import sqlite3
try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError:
    psycopg = None
    dict_row = None
from functools import wraps
from datetime import datetime
from zoneinfo import ZoneInfo
import os
import secrets

app = Flask(__name__)
TZ = ZoneInfo("America/Sao_Paulo")

def parse_money(value, default=0.0):
    """Parse monetary input in Brazilian or standard notation.

    59.99 -> 59.99
    59,99 -> 59.99
    1.399,99 -> 1399.99
    1,399.99 -> 1399.99
    """
    try:
        text = str(value if value is not None else default).strip()
        text = text.replace("R$", "").replace(" ", "")
        if not text:
            return float(default)
        if "," in text and "." in text:
            if text.rfind(",") > text.rfind("."):
                text = text.replace(".", "").replace(",", ".")
            else:
                text = text.replace(",", "")
        elif "," in text:
            text = text.replace(",", ".")
        return float(text)
    except (ValueError, TypeError):
        try:
            return float(value or default)
        except (ValueError, TypeError):
            return float(default)

def table_columns(conn, table):
    if conn.postgres:
        return {r["column_name"] for r in conn.execute("SELECT column_name FROM information_schema.columns WHERE table_name = ?", (table,)).fetchall()}
    return {r[1] for r in conn.execute(f"PRAGMA table_info({table})").fetchall()}

def add_column_if_missing(conn, table, column, definition):
    if column not in table_columns(conn, table):
        conn.execute(f"ALTER TABLE {table} ADD COLUMN {column} {definition}")

app.secret_key = os.environ.get("SECRET_KEY", "dev-only-change-this-secret")
DB = os.path.join(os.path.dirname(os.path.abspath(__file__)), "loja.db")
DATABASE_URL = os.environ.get("DATABASE_URL")


class DBWrapper:
    """Small compatibility wrapper so the existing app can use SQLite locally
    or PostgreSQL/Neon in production without changing every query by hand.
    """
    def __init__(self, conn, postgres=False):
        self._conn = conn
        self.postgres = postgres

    def _sql(self, sql):
        if self.postgres:
            # The original app uses SQLite's ? placeholders.
            return sql.replace("?", "%s")
        return sql

    def execute(self, sql, params=None):
        return self._conn.execute(self._sql(sql), params or ())

    def executescript(self, script):
        if not self.postgres:
            return self._conn.executescript(script)

        # PostgreSQL schema used below is already written as separate statements.
        for statement in script.split(";"):
            statement = statement.strip()
            if statement:
                self._conn.execute(statement)

    def commit(self):
        return self._conn.commit()

    def rollback(self):
        return self._conn.rollback()

    def close(self):
        return self._conn.close()


def db():
    if DATABASE_URL:
        if psycopg is None:
            raise RuntimeError(
                "A biblioteca psycopg não está instalada. "
                "Adicione psycopg[binary] ao requirements.txt."
            )
        conn = psycopg.connect(DATABASE_URL, row_factory=dict_row)
        return DBWrapper(conn, postgres=True)

    conn = sqlite3.connect(DB)
    conn.row_factory = sqlite3.Row
    return DBWrapper(conn, postgres=False)


def init_db():
    conn = db()

    if conn.postgres:
        schema = """
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username TEXT UNIQUE NOT NULL,
            password TEXT NOT NULL,
            role TEXT NOT NULL DEFAULT 'admin',
            active BOOLEAN NOT NULL DEFAULT TRUE
        );

        CREATE TABLE IF NOT EXISTS products (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            category TEXT NOT NULL,
            brand TEXT,
            color TEXT,
            size TEXT,
            price DOUBLE PRECISION NOT NULL DEFAULT 0,
            stock INTEGER NOT NULL DEFAULT 0,
            min_stock INTEGER NOT NULL DEFAULT 0,
            cost DOUBLE PRECISION NOT NULL DEFAULT 0,
            barcode TEXT,
            supplier_id INTEGER,
            image_url TEXT,
            created_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS movements (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            product_id INTEGER NOT NULL,
            type TEXT NOT NULL,
            quantity INTEGER NOT NULL,
            note TEXT,
            created_at TEXT NOT NULL,
            FOREIGN KEY(product_id) REFERENCES products(id)
        );

        CREATE TABLE IF NOT EXISTS sales (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            total DOUBLE PRECISION NOT NULL DEFAULT 0,
            payment_method TEXT NOT NULL,
            username TEXT NOT NULL,
            created_at TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'COMPLETED',
            sale_number INTEGER
        );

        CREATE TABLE IF NOT EXISTS sale_items (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sale_id INTEGER NOT NULL,
            product_id INTEGER NOT NULL,
            quantity INTEGER NOT NULL,
            unit_price DOUBLE PRECISION NOT NULL,
            unit_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
            subtotal DOUBLE PRECISION NOT NULL,
            FOREIGN KEY(sale_id) REFERENCES sales(id),
            FOREIGN KEY(product_id) REFERENCES products(id)
        );

        CREATE TABLE IF NOT EXISTS audit_logs (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username TEXT NOT NULL,
            action TEXT NOT NULL,
            details TEXT,
            created_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS auth_sessions (
            token TEXT PRIMARY KEY,
            user_id INTEGER NOT NULL,
            created_at TEXT NOT NULL,
            FOREIGN KEY(user_id) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS cash_sessions (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            opening_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
            closing_amount DOUBLE PRECISION,
            expected_amount DOUBLE PRECISION,
            difference DOUBLE PRECISION,
            opened_by TEXT NOT NULL,
            closed_by TEXT,
            opened_at TEXT NOT NULL,
            closed_at TEXT,
            status TEXT NOT NULL DEFAULT 'OPEN'
        );
        

        CREATE TABLE IF NOT EXISTS suppliers (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL, cnpj TEXT, phone TEXT, whatsapp TEXT, email TEXT, address TEXT, created_at TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS cash_movements (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, cash_session_id INTEGER, type TEXT NOT NULL, amount DOUBLE PRECISION NOT NULL, description TEXT, username TEXT NOT NULL, created_at TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS returns (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sale_id INTEGER NOT NULL, type TEXT NOT NULL, reason TEXT, difference DOUBLE PRECISION NOT NULL DEFAULT 0, username TEXT NOT NULL, created_at TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS return_items (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, return_id INTEGER NOT NULL, sale_item_id INTEGER NOT NULL, product_id INTEGER NOT NULL, quantity INTEGER NOT NULL, replacement_product_id INTEGER, replacement_quantity INTEGER NOT NULL DEFAULT 0
        );
        CREATE TABLE IF NOT EXISTS categories (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT UNIQUE NOT NULL);
        """
        conn.executescript(schema)
        # Em bancos PostgreSQL já existentes, a coluna active pode ainda não existir.
        # Verificamos antes de alterar para não abortar a transação.
        col = conn.execute(
            "SELECT 1 FROM information_schema.columns WHERE table_name = ? AND column_name = ?",
            ("users", "active")
        ).fetchone()
        if not col:
            conn.execute("ALTER TABLE users ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE")
        conn.commit()
    else:
        conn.executescript("""
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT UNIQUE NOT NULL,
            password TEXT NOT NULL,
            role TEXT NOT NULL DEFAULT 'admin',
            active INTEGER NOT NULL DEFAULT 1
        );

        CREATE TABLE IF NOT EXISTS products (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            category TEXT NOT NULL,
            brand TEXT,
            color TEXT,
            size TEXT,
            price REAL NOT NULL DEFAULT 0,
            stock INTEGER NOT NULL DEFAULT 0,
            min_stock INTEGER NOT NULL DEFAULT 0,
            cost REAL NOT NULL DEFAULT 0,
            barcode TEXT,
            supplier_id INTEGER,
            image_url TEXT,
            created_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS movements (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            product_id INTEGER NOT NULL,
            type TEXT NOT NULL,
            quantity INTEGER NOT NULL,
            note TEXT,
            created_at TEXT NOT NULL,
            FOREIGN KEY(product_id) REFERENCES products(id)
        );

        CREATE TABLE IF NOT EXISTS sales (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            total REAL NOT NULL DEFAULT 0,
            payment_method TEXT NOT NULL,
            username TEXT NOT NULL,
            created_at TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'COMPLETED',
            sale_number INTEGER
        );

        CREATE TABLE IF NOT EXISTS sale_items (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            sale_id INTEGER NOT NULL,
            product_id INTEGER NOT NULL,
            quantity INTEGER NOT NULL,
            unit_price REAL NOT NULL,
            unit_cost REAL NOT NULL DEFAULT 0,
            subtotal REAL NOT NULL,
            FOREIGN KEY(sale_id) REFERENCES sales(id),
            FOREIGN KEY(product_id) REFERENCES products(id)
        );

        CREATE TABLE IF NOT EXISTS audit_logs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT NOT NULL,
            action TEXT NOT NULL,
            details TEXT,
            created_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS auth_sessions (
            token TEXT PRIMARY KEY,
            user_id INTEGER NOT NULL,
            created_at TEXT NOT NULL,
            FOREIGN KEY(user_id) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS cash_sessions (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            opening_amount REAL NOT NULL DEFAULT 0,
            closing_amount REAL,
            expected_amount REAL,
            difference REAL,
            opened_by TEXT NOT NULL,
            closed_by TEXT,
            opened_at TEXT NOT NULL,
            closed_at TEXT,
            status TEXT NOT NULL DEFAULT 'OPEN'
        );
        

        CREATE TABLE IF NOT EXISTS suppliers (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, cnpj TEXT, phone TEXT, whatsapp TEXT, email TEXT, address TEXT, created_at TEXT NOT NULL);
        CREATE TABLE IF NOT EXISTS cash_movements (id INTEGER PRIMARY KEY AUTOINCREMENT, cash_session_id INTEGER, type TEXT NOT NULL, amount REAL NOT NULL, description TEXT, username TEXT NOT NULL, created_at TEXT NOT NULL);
        CREATE TABLE IF NOT EXISTS returns (id INTEGER PRIMARY KEY AUTOINCREMENT, sale_id INTEGER NOT NULL, type TEXT NOT NULL, reason TEXT, difference REAL NOT NULL DEFAULT 0, username TEXT NOT NULL, created_at TEXT NOT NULL);
        CREATE TABLE IF NOT EXISTS return_items (id INTEGER PRIMARY KEY AUTOINCREMENT, return_id INTEGER NOT NULL, sale_item_id INTEGER NOT NULL, product_id INTEGER NOT NULL, quantity INTEGER NOT NULL, replacement_product_id INTEGER, replacement_quantity INTEGER NOT NULL DEFAULT 0);
        CREATE TABLE IF NOT EXISTS categories (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT UNIQUE NOT NULL);
        """)

    # Migrations for the complete store-management module.
    add_column_if_missing(conn, "products", "cost", "DOUBLE PRECISION NOT NULL DEFAULT 0" if conn.postgres else "REAL NOT NULL DEFAULT 0")
    add_column_if_missing(conn, "products", "barcode", "TEXT")
    add_column_if_missing(conn, "products", "supplier_id", "INTEGER")
    add_column_if_missing(conn, "products", "image_url", "TEXT")
    add_column_if_missing(conn, "sales", "status", "TEXT NOT NULL DEFAULT 'COMPLETED'")
    add_column_if_missing(conn, "sales", "sale_number", "INTEGER")
    add_column_if_missing(conn, "sales", "sale_token", "TEXT")
    add_column_if_missing(conn, "sale_items", "unit_cost", "DOUBLE PRECISION NOT NULL DEFAULT 0" if conn.postgres else "REAL NOT NULL DEFAULT 0")
    conn.execute("UPDATE sales SET status='COMPLETED' WHERE status IS NULL OR status=''" )
    # Backfill sale item cost from current product cost where historical cost is unavailable.
    try:
        conn.execute("UPDATE sale_items SET unit_cost = COALESCE((SELECT cost FROM products WHERE products.id = sale_items.product_id),0) WHERE unit_cost = 0")
    except Exception:
        pass
    # Default categories for new installations.
    for cname in ["Roupa","Calçado","Acessório","Outro"]:
        try: conn.execute("INSERT INTO categories (name) VALUES (?) ON CONFLICT (name) DO NOTHING" if conn.postgres else "INSERT OR IGNORE INTO categories (name) VALUES (?)", (cname,))
        except Exception: pass

    # Migrations for customers and enhanced sales.
    # Existing Neon/SQLite data is preserved.
    if conn.postgres:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS customers (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                cpf TEXT,
                phone TEXT,
                whatsapp TEXT,
                address TEXT,
                created_at TEXT NOT NULL
            )
        """)
        # Migra instalações antigas de clientes sem apagar os dados existentes.
        customer_cols = {
            row["column_name"] for row in conn.execute(
                "SELECT column_name FROM information_schema.columns WHERE table_name = 'customers'"
            ).fetchall()
        }
        if "cpf" not in customer_cols:
            conn.execute("ALTER TABLE customers ADD COLUMN cpf TEXT")
        if "phone" not in customer_cols:
            conn.execute("ALTER TABLE customers ADD COLUMN phone TEXT")
        if "whatsapp" not in customer_cols:
            conn.execute("ALTER TABLE customers ADD COLUMN whatsapp TEXT")
        if "address" not in customer_cols:
            conn.execute("ALTER TABLE customers ADD COLUMN address TEXT")
        if "created_at" not in customer_cols:
            conn.execute("ALTER TABLE customers ADD COLUMN created_at TEXT")
            conn.execute("UPDATE customers SET created_at = ? WHERE created_at IS NULL", (datetime.now(TZ).strftime("%Y-%m-%d %H:%M:%S"),))

        cols = {
            row["column_name"] for row in conn.execute(
                "SELECT column_name FROM information_schema.columns WHERE table_name = 'sales'"
            ).fetchall()
        }
        if "customer_id" not in cols:
            conn.execute("ALTER TABLE sales ADD COLUMN customer_id INTEGER")
        if "subtotal" not in cols:
            conn.execute("ALTER TABLE sales ADD COLUMN subtotal DOUBLE PRECISION NOT NULL DEFAULT 0")
        if "discount_percent" not in cols:
            conn.execute("ALTER TABLE sales ADD COLUMN discount_percent DOUBLE PRECISION NOT NULL DEFAULT 0")
        if "cash_session_id" not in cols:
            conn.execute("ALTER TABLE sales ADD COLUMN cash_session_id INTEGER")
        if "sale_number" not in cols:
            conn.execute("ALTER TABLE sales ADD COLUMN sale_number INTEGER")
        if "sale_token" not in cols:
            conn.execute("ALTER TABLE sales ADD COLUMN sale_token TEXT")
        # Preenche o número exibido das vendas antigas sem alterar o ID interno.
        existing_sales = conn.execute("SELECT id, sale_number FROM sales WHERE status <> 'CANCELLED' ORDER BY id").fetchall()
        next_number = 1
        for old_sale in existing_sales:
            if old_sale["sale_number"] is None:
                conn.execute("UPDATE sales SET sale_number = ? WHERE id = ?", (next_number, old_sale["id"]))
            next_number += 1
        conn.execute("UPDATE sales SET subtotal = total WHERE subtotal = 0 AND total <> 0")
        conn.execute("CREATE UNIQUE INDEX IF NOT EXISTS ux_sales_sale_token ON sales(sale_token)")
        conn.commit()
    else:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS customers (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                cpf TEXT,
                phone TEXT,
                whatsapp TEXT,
                address TEXT,
                created_at TEXT NOT NULL
            )
        """)
        cols = {row[1] for row in conn.execute("PRAGMA table_info(sales)").fetchall()}
        if "customer_id" not in cols:
            conn.execute("ALTER TABLE sales ADD COLUMN customer_id INTEGER")
        if "subtotal" not in cols:
            conn.execute("ALTER TABLE sales ADD COLUMN subtotal REAL NOT NULL DEFAULT 0")
        if "discount_percent" not in cols:
            conn.execute("ALTER TABLE sales ADD COLUMN discount_percent REAL NOT NULL DEFAULT 0")
        if "cash_session_id" not in cols:
            conn.execute("ALTER TABLE sales ADD COLUMN cash_session_id INTEGER")
        if "sale_number" not in cols:
            conn.execute("ALTER TABLE sales ADD COLUMN sale_number INTEGER")
        # Preenche o número exibido das vendas antigas sem alterar o ID interno.
        existing_sales = conn.execute("SELECT id, sale_number FROM sales WHERE status <> 'CANCELLED' ORDER BY id").fetchall()
        next_number = 1
        for old_sale in existing_sales:
            if old_sale["sale_number"] is None:
                conn.execute("UPDATE sales SET sale_number = ? WHERE id = ?", (next_number, old_sale["id"]))
            next_number += 1
        conn.execute("UPDATE sales SET subtotal = total WHERE subtotal = 0 AND total <> 0")
        conn.commit()

    # Cria somente usuários que ainda não existem.
    # Depois do primeiro cadastro, senha, perfil e status são administrados
    # pela tela de Usuários e não são sobrescritos no deploy.
    seed_users = os.environ.get(
        "SEED_USERS",
        "admin:admin123,Pedro:Pyetro123,Roberta:Pyetro123"
    )

    for item in seed_users.split(","):
        item = item.strip()
        if not item:
            continue
        try:
            username, senha = item.split(":", 1)
        except ValueError:
            continue

        username = username.strip()
        senha = senha.strip()
        if not username or not senha:
            continue

        existente = conn.execute(
            "SELECT id FROM users WHERE LOWER(username) = LOWER(?)",
            (username,)
        ).fetchone()

        if not existente:
            role = "admin" if username.lower() == "admin" else "operator"
            conn.execute(
                "INSERT INTO users (username, password, role, active) VALUES (?, ?, ?, ?)",
                (username, generate_password_hash(senha), role, True)
            )

    # A conta principal "admin" sempre permanece administradora e ativa.
    conn.execute(
        "UPDATE users SET role = 'admin', active = ? WHERE LOWER(username) = 'admin'",
        (True,)
    )

    # Corrige registros antigos que não tenham active.
    conn.execute("UPDATE users SET active = ? WHERE active IS NULL", (True,))

    conn.commit()
    conn.close()


try:
    init_db()
except Exception as exc:
    # Keep the Render log explicit instead of hiding the real startup error.
    raise RuntimeError(f"Falha ao inicializar o banco: {exc}") from exc


def login_required(fn):
    @wraps(fn)
    def wrapper(*args, **kwargs):
        if not get_current_user():
            return redirect(url_for("login"))
        return fn(*args, **kwargs)
    return wrapper


@app.before_request
def load_current_user():
    """Autenticação server-side: o navegador guarda apenas um token aleatório.
    O usuário real é sempre recuperado do Neon pelo token, eliminando mistura
    de contas entre páginas/abas e qualquer dependência de nome/perfil em cookie.
    """
    g.current_user = None
    token = request.cookies.get("pyetro_auth")
    if not token:
        return None

    conn = None
    try:
        conn = db()
        user = conn.execute(
            """SELECT u.id, u.username, u.role, u.active
               FROM auth_sessions s
               JOIN users u ON u.id = s.user_id
               WHERE s.token = ?""",
            (token,)
        ).fetchone()
    except Exception:
        user = None
    finally:
        if conn is not None:
            conn.close()

    if not user or not bool(user["active"]):
        return None

    g.current_user = user
    return None


def get_current_user():
    return getattr(g, "current_user", None)


@app.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form.get("username", "").strip()
        password = request.form.get("password", "")

        conn = db()
        try:
            user = conn.execute(
                "SELECT * FROM users WHERE LOWER(username) = LOWER(?)",
                (username,)
            ).fetchone()

            if user and not bool(user["active"]):
                flash("Este usuário está desativado. Procure o administrador.", "danger")
                return render_template("login.html")

            if not user or not check_password_hash(user["password"], password):
                flash("Usuário ou senha inválidos.", "danger")
                return render_template("login.html")

            # Cada login recebe um token novo e independente. O token aponta
            # para o ID exato do usuário no Neon; nenhuma página precisa confiar
            # em username/role vindos de cookie.
            token = secrets.token_urlsafe(48)
            now = datetime.now(TZ).strftime("%Y-%m-%d %H:%M:%S")
            conn.execute("DELETE FROM auth_sessions WHERE user_id = ?", (int(user["id"]),))
            conn.execute(
                "INSERT INTO auth_sessions (token, user_id, created_at) VALUES (?, ?, ?)",
                (token, int(user["id"]), now)
            )
            conn.commit()
        finally:
            conn.close()

        # Limpa apenas dados antigos da sessão Flask (ex.: carrinho), sem usar
        # a sessão para autenticação.
        session.clear()
        session.permanent = False

        target = "admin_dashboard" if user["role"] == "admin" else "dashboard"
        response = make_response(redirect(url_for(target)))
        response.set_cookie(
            "pyetro_auth", token, httponly=True, samesite="Lax",
            secure=request.is_secure, max_age=60 * 60 * 24 * 7, path="/"
        )
        response.headers["Cache-Control"] = "no-store, no-cache, must-revalidate, max-age=0"
        response.headers["Pragma"] = "no-cache"
        response.headers["Expires"] = "0"
        return response

    return render_template("login.html")


@app.route("/logout")
def logout():
    token = request.cookies.get("pyetro_auth")
    if token:
        conn = db()
        try:
            conn.execute("DELETE FROM auth_sessions WHERE token = ?", (token,))
            conn.commit()
        finally:
            conn.close()
    session.clear()
    response = make_response(redirect(url_for("login")))
    response.delete_cookie("pyetro_auth", path="/")
    return response


def admin_required(fn):
    @wraps(fn)
    def wrapper(*args, **kwargs):
        user = get_current_user()
        if not user:
            return redirect(url_for("login"))
        if user["role"] != "admin":
            flash("Acesso restrito ao administrador.", "danger")
            return redirect(url_for("dashboard"))
        return fn(*args, **kwargs)
    return wrapper


@app.context_processor
def inject_user_context():
    user = get_current_user()
    return {
        "current_username": user["username"] if user else "",
        "current_role": user["role"] if user else "operator",
        "is_admin": bool(user and user["role"] == "admin"),
        "now_display": datetime.now(TZ).strftime("%d/%m/%Y %H:%M"),
    }


@app.after_request
def prevent_authenticated_page_cache(response):
    # Evita que o navegador reapresente uma página antiga de outro usuário.
    if request.cookies.get("pyetro_auth"):
        response.headers["Cache-Control"] = "no-store, no-cache, must-revalidate, max-age=0"
        response.headers["Pragma"] = "no-cache"
        response.headers["Expires"] = "0"
        response.headers["Vary"] = "Cookie"
    return response


def audit(action, details=""):
    """Registra ações administrativas e operacionais importantes."""
    try:
        conn = db()
        conn.execute(
            """INSERT INTO audit_logs (username, action, details, created_at)
               VALUES (?, ?, ?, ?)""",
            (
                (get_current_user()["username"] if get_current_user() else "sistema"),
                action,
                details,
                datetime.now(TZ).strftime("%Y-%m-%d %H:%M:%S"),
            )
        )
        conn.commit()
        conn.close()
    except Exception:
        # Auditoria nunca deve derrubar uma operação válida.
        pass


@app.route("/admin")
@login_required
@admin_required
def admin_dashboard():
    conn = db()

    total_products = conn.execute("SELECT COUNT(*) c FROM products").fetchone()["c"]
    total_stock = conn.execute("SELECT COALESCE(SUM(stock), 0) s FROM products").fetchone()["s"]
    low_stock = conn.execute("SELECT COUNT(*) c FROM products WHERE stock <= min_stock").fetchone()["c"]
    total_sales = conn.execute("SELECT COUNT(*) c FROM sales WHERE status <> 'CANCELLED'").fetchone()["c"]
    total_revenue = conn.execute("SELECT COALESCE(SUM(total), 0) v FROM sales WHERE status <> 'CANCELLED'").fetchone()["v"]
    total_users = conn.execute("SELECT COUNT(*) c FROM users").fetchone()["c"]

    movements = conn.execute("""
        SELECT m.*, p.name
        FROM movements m JOIN products p ON p.id = m.product_id
        ORDER BY m.id DESC LIMIT 8
    """).fetchall()

    conn.close()
    return render_template(
        "admin_dashboard.html",
        total_products=total_products,
        total_stock=total_stock,
        low_stock=low_stock,
        total_sales=total_sales,
        total_revenue=float(total_revenue or 0),
        # Nomes esperados pelo template atual do painel ADM
        sales_count=total_sales,
        revenue=float(total_revenue or 0),
        total_users=total_users,
        movements=movements
    )


@app.route("/dashboard")
@login_required
def dashboard():
    conn = db()

    total_products = conn.execute(
        "SELECT COUNT(*) c FROM products"
    ).fetchone()["c"]

    total_stock = conn.execute(
        "SELECT COALESCE(SUM(stock), 0) s FROM products"
    ).fetchone()["s"]

    low_stock = conn.execute(
        "SELECT COUNT(*) c FROM products WHERE stock <= min_stock"
    ).fetchone()["c"]

    today = datetime.now(TZ).strftime("%Y-%m-%d")
    month_period = datetime.now(TZ).strftime("%Y-%m")
    today_summary = conn.execute("""
        SELECT COUNT(*) sales_count, COALESCE(SUM(total),0) revenue
        FROM sales WHERE status <> 'CANCELLED' AND substr(created_at,1,10)=?
    """, (today,)).fetchone()
    month_summary = conn.execute("""
        SELECT COUNT(*) sales_count, COALESCE(SUM(total),0) revenue
        FROM sales WHERE status <> 'CANCELLED' AND substr(created_at,1,7)=?
    """, (month_period,)).fetchone()
    low_products = conn.execute("""
        SELECT id,name,brand,color,size,stock,min_stock
        FROM products WHERE stock <= min_stock
        ORDER BY stock ASC, name ASC LIMIT 8
    """).fetchall()
    open_cash = conn.execute("""
        SELECT * FROM cash_sessions WHERE status='OPEN' ORDER BY id DESC LIMIT 1
    """).fetchone()

    movements = conn.execute("""
        SELECT m.*, p.name
        FROM movements m
        JOIN products p ON p.id = m.product_id
        ORDER BY m.id DESC
        LIMIT 10
    """).fetchall()

    conn.close()

    response = make_response(render_template(
        "dashboard.html",
        total_products=total_products,
        total_stock=total_stock,
        low_stock=low_stock,
        movements=movements,
        today_revenue=float(today_summary["revenue"] or 0),
        today_sales=int(today_summary["sales_count"] or 0),
        month_revenue=float(month_summary["revenue"] or 0),
        month_sales=int(month_summary["sales_count"] or 0),
        low_products=low_products,
        open_cash=open_cash
    ))
    response.headers["Cache-Control"] = "no-store, no-cache, must-revalidate, max-age=0"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "0"
    return response


@app.route("/")
def root():
    return redirect(url_for("dashboard")) if get_current_user() else redirect(url_for("login"))


@app.route("/products")
@login_required
def products():
    search = request.args.get("search", "").strip()
    conn = db()

    if search:
        term = f"%{search}%"
        rows = conn.execute("""
            SELECT * FROM products
            WHERE name LIKE ?
               OR brand LIKE ?
               OR COALESCE(barcode,'') LIKE ?
               OR color LIKE ?
               OR size LIKE ?
            ORDER BY id DESC
        """, (term, term, term, term, term)).fetchall()
    else:
        rows = conn.execute(
            "SELECT * FROM products ORDER BY id DESC"
        ).fetchall()

    conn.close()
    return render_template("products.html", products=rows, search=search)


@app.route("/products/new", methods=["GET", "POST"])
@login_required
def new_product():
    if request.method == "POST":
        stock = int(request.form.get("stock") or 0)

        data = (
            request.form["name"].strip(), request.form.get("category", "Outro").strip(),
            request.form.get("brand", "").strip(), request.form.get("color", "").strip(),
            request.form.get("size", "").strip(), parse_money(request.form.get("price")),
            stock, int(request.form.get("min_stock") or 0), parse_money(request.form.get("cost")),
            request.form.get("barcode", "").strip() or None, int(request.form.get("supplier_id") or 0) or None,
            request.form.get("image_url", "").strip() or None, datetime.now(TZ).strftime("%Y-%m-%d %H:%M:%S")
        )

        conn = db()

        if conn.postgres:
            cur = conn.execute("""
                INSERT INTO products
                (name, category, brand, color, size, price, stock, min_stock, cost, barcode, supplier_id, image_url, created_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                RETURNING id
            """, data)
            product_id = cur.fetchone()["id"]
        else:
            cur = conn.execute("""
                INSERT INTO products
                (name, category, brand, color, size, price, stock, min_stock, cost, barcode, supplier_id, image_url, created_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, data)
            product_id = cur.lastrowid

        if stock > 0:
            conn.execute("""
                INSERT INTO movements
                (product_id, type, quantity, note, created_at)
                VALUES (?, ?, ?, ?, ?)
            """, (
                product_id,
                "ENTRADA",
                stock,
                "Estoque inicial",
                datetime.now(TZ).strftime("%Y-%m-%d %H:%M:%S")
            ))

        conn.commit()
        conn.close()

        flash("Produto cadastrado com sucesso.", "success")
        return redirect(url_for("products"))

    conn = db(); suppliers = conn.execute("SELECT * FROM suppliers ORDER BY name").fetchall(); categories = conn.execute("SELECT * FROM categories ORDER BY name").fetchall(); conn.close()
    return render_template("product_form.html", product=None, suppliers=suppliers, categories=categories)


@app.route("/products/<int:product_id>/edit", methods=["GET", "POST"])
@login_required
def edit_product(product_id):
    conn = db()
    product = conn.execute(
        "SELECT * FROM products WHERE id = ?",
        (product_id,)
    ).fetchone()

    if not product:
        conn.close()
        return "Produto não encontrado", 404

    if request.method == "POST":
        conn.execute("""
            UPDATE products
            SET name = ?, category = ?, brand = ?, color = ?, size = ?,
                price = ?, min_stock = ?, cost = ?, barcode = ?, supplier_id = ?, image_url = ?
            WHERE id = ?
        """, (
            request.form["name"].strip(),
            request.form["category"],
            request.form.get("brand", "").strip(),
            request.form.get("color", "").strip(),
            request.form.get("size", "").strip(),
            parse_money(request.form.get("price")), int(request.form.get("min_stock") or 0),
            parse_money(request.form.get("cost")), request.form.get("barcode", "").strip() or None,
            int(request.form.get("supplier_id") or 0) or None, request.form.get("image_url", "").strip() or None, product_id
        ))

        conn.commit()
        conn.close()

        flash("Produto atualizado.", "success")
        return redirect(url_for("products"))

    suppliers = conn.execute("SELECT * FROM suppliers ORDER BY name").fetchall()
    categories = conn.execute("SELECT * FROM categories ORDER BY name").fetchall()
    conn.close()
    return render_template("product_form.html", product=product, suppliers=suppliers, categories=categories)


@app.post("/products/<int:product_id>/delete")
@login_required
@admin_required
def delete_product(product_id):
    """Exclui um produto sem quebrar o histórico de vendas."""
    conn = db()

    try:
        product = conn.execute(
            "SELECT id, name FROM products WHERE id = ?",
            (product_id,)
        ).fetchone()

        if not product:
            flash("Produto não encontrado.", "danger")
            return redirect(url_for("products"))

        # Produtos que já foram vendidos permanecem no cadastro para
        # preservar o histórico e os relatórios de vendas.
        sold = conn.execute(
            "SELECT COUNT(*) AS c FROM sale_items WHERE product_id = ?",
            (product_id,)
        ).fetchone()

        if int(sold["c"] or 0) > 0:
            flash(
                f"Não é possível excluir '{product['name']}' porque ele já "
                "está vinculado a uma venda. O histórico de vendas foi preservado.",
                "warning"
            )
            return redirect(url_for("products"))

        # Se nunca foi vendido, remove os movimentos e o produto.
        conn.execute(
            "DELETE FROM movements WHERE product_id = ?",
            (product_id,)
        )
        conn.execute(
            "DELETE FROM products WHERE id = ?",
            (product_id,)
        )

        conn.commit()
        audit("EXCLUSÃO DE PRODUTO", f"Produto #{product_id} - {product['name']}")
        flash(f"Produto '{product['name']}' excluído com sucesso.", "success")

    except Exception as exc:
        conn.rollback()
        flash(f"Não foi possível excluir o produto: {exc}", "danger")

    finally:
        conn.close()

    return redirect(url_for("products"))


@app.route("/stock/<int:product_id>", methods=["GET", "POST"])
@login_required
def stock(product_id):
    conn = db()

    product = conn.execute(
        "SELECT * FROM products WHERE id = ?",
        (product_id,)
    ).fetchone()

    if not product:
        conn.close()
        return "Produto não encontrado", 404

    if request.method == "POST":
        movement_type = request.form["type"]
        quantity = int(request.form["quantity"])
        note = request.form.get("note", "").strip()

        if quantity <= 0:
            flash("A quantidade deve ser maior que zero.", "danger")

        elif movement_type == "SAIDA" and quantity > product["stock"]:
            flash("Estoque insuficiente para essa saída.", "danger")

        else:
            if movement_type == "ENTRADA":
                new_stock = product["stock"] + quantity
            else:
                new_stock = product["stock"] - quantity

            conn.execute(
                "UPDATE products SET stock = ? WHERE id = ?",
                (new_stock, product_id)
            )

            conn.execute("""
                INSERT INTO movements
                (product_id, type, quantity, note, created_at)
                VALUES (?, ?, ?, ?, ?)
            """, (
                product_id,
                movement_type,
                quantity,
                note,
                datetime.now(TZ).strftime("%Y-%m-%d %H:%M:%S")
            ))

            conn.commit()
            conn.close()

            flash(f"{movement_type.title()} registrada com sucesso.", "success")
            return redirect(url_for("stock", product_id=product_id))

    movements = conn.execute("""
        SELECT * FROM movements
        WHERE product_id = ?
        ORDER BY id DESC
    """, (product_id,)).fetchall()

    conn.close()

    return render_template(
        "stock.html",
        product=product,
        movements=movements
    )


@app.route("/movements")
@login_required
def movements():
    conn = db()

    rows = conn.execute("""
        SELECT m.*, p.name
        FROM movements m
        JOIN products p ON p.id = m.product_id
        ORDER BY m.id DESC
    """).fetchall()

    conn.close()

    return render_template(
        "movements.html",
        movements=rows
    )




@app.route("/sales")
@login_required
def sales():
    conn = db()
    rows = conn.execute("""
        SELECT s.*, COUNT(si.id) AS item_count,
               COALESCE(c.name, '') AS customer_name
        FROM sales s
        LEFT JOIN sale_items si ON si.sale_id = s.id
        LEFT JOIN customers c ON c.id = s.customer_id
        WHERE s.status <> 'CANCELLED'
        GROUP BY s.id, c.name
        ORDER BY s.id ASC
    """).fetchall()
    # display_number é a sequência atual das vendas existentes.
    # Assim, se uma venda for excluída, não ficam buracos na numeração exibida.
    display_rows = []
    total_rows = len(rows)
    for index, row in enumerate(rows, start=1):
        data = dict(row)
        data["display_number"] = index
        data["status"] = data.get("status", "COMPLETED")
        display_rows.append(data)
    display_rows.reverse()
    conn.close()
    return render_template("sales.html", sales=display_rows)


@app.route("/sales/new", methods=["GET", "POST"])
@login_required
def new_sale():
    cart = session.get("sale_cart", [])

    if request.method == "POST":
        action = request.form.get("action")

        if action == "clear":
            session.pop("sale_cart", None)
            flash("Venda limpa.", "info")
            return redirect(url_for("new_sale"))

        if action == "add":
            try:
                product_id = int(request.form.get("product_id") or 0)
                quantity = int(request.form.get("quantity") or 0)
            except (ValueError, TypeError):
                flash("Selecione um produto e informe uma quantidade válida.", "danger")
                return redirect(url_for("new_sale"))
            if quantity <= 0:
                flash("A quantidade deve ser maior que zero.", "danger")
                return redirect(url_for("new_sale"))

            conn = db()
            barcode = request.form.get("barcode", "").strip()
            if barcode:
                product = conn.execute("SELECT * FROM products WHERE barcode = ? LIMIT 1", (barcode,)).fetchone()
            else:
                product = conn.execute("SELECT * FROM products WHERE id = ?", (product_id,)).fetchone()
            conn.close()
            if not product:
                flash("Produto não encontrado.", "danger")
                return redirect(url_for("new_sale"))

            product_id = int(product["id"]); existing_qty = next((i["quantity"] for i in cart if i["product_id"] == product_id), 0)
            if existing_qty + quantity > product["stock"]:
                flash(f"Estoque insuficiente. Disponível: {product['stock']}.", "danger")
                return redirect(url_for("new_sale"))

            found = False
            for item in cart:
                if item["product_id"] == product_id:
                    item["quantity"] += quantity
                    found = True
                    break
            if not found:
                cart.append({
                    "product_id": product["id"], "name": product["name"],
                    "category": product["category"], "brand": product["brand"] or "",
                    "color": product["color"] or "", "size": product["size"] or "",
                    "quantity": quantity, "unit_price": float(product["price"])
                })
            session["sale_cart"] = cart
            return redirect(url_for("new_sale"))

        if action == "remove":
            try:
                product_id = int(request.form["product_id"])
                cart = [i for i in cart if i["product_id"] != product_id]
                session["sale_cart"] = cart
            except (ValueError, TypeError):
                pass
            return redirect(url_for("new_sale"))

        if action == "finish":
            if not cart:
                flash("Adicione pelo menos um produto à venda.", "danger")
                return redirect(url_for("new_sale"))

            payment_method = request.form.get("payment_method", "").strip()
            allowed = {"PIX", "Dinheiro", "Cartão de débito", "Cartão de crédito"}
            if payment_method not in allowed:
                flash("Selecione uma forma de pagamento.", "danger")
                return redirect(url_for("new_sale"))

            try:
                # Aceita tanto 10.5 quanto 10,5 no padrão brasileiro.
                discount_raw = (request.form.get("discount_percent") or "0").strip().replace(",", ".")
                discount_percent = float(discount_raw)
            except (ValueError, TypeError):
                discount_percent = 0
            if discount_percent < 0 or discount_percent > 100:
                flash("O desconto deve estar entre 0% e 100%.", "danger")
                return redirect(url_for("new_sale"))

            customer_id_raw = request.form.get("customer_id", "").strip()
            customer_id = None
            if customer_id_raw:
                try:
                    customer_id = int(customer_id_raw)
                except ValueError:
                    flash("Cliente inválido.", "danger")
                    return redirect(url_for("new_sale"))

            conn = db()
            try:
                if customer_id is not None:
                    customer = conn.execute("SELECT id FROM customers WHERE id = ?", (customer_id,)).fetchone()
                    if not customer:
                        raise ValueError("Cliente não encontrado.")

                checked = []
                subtotal_total = 0.0
                for item in cart:
                    product = conn.execute("SELECT * FROM products WHERE id = ?", (item["product_id"],)).fetchone()
                    if not product:
                        raise ValueError(f"Produto '{item['name']}' não existe mais.")
                    if item["quantity"] > product["stock"]:
                        raise ValueError(f"Estoque insuficiente para '{product['name']}'. Disponível: {product['stock']}.")
                    unit_price = float(product["price"])
                    subtotal = unit_price * item["quantity"]
                    subtotal_total += subtotal
                    checked.append((product, item["quantity"], unit_price, subtotal))

                discount_value = subtotal_total * (discount_percent / 100.0)
                total = round(subtotal_total - discount_value, 2)
                now = datetime.now(TZ).strftime("%Y-%m-%d %H:%M:%S")
                username = get_current_user()["username"] if get_current_user() else "admin"
                open_cash = conn.execute(
                    "SELECT id FROM cash_sessions WHERE status='OPEN' ORDER BY id DESC LIMIT 1"
                ).fetchone()
                cash_session_id = open_cash["id"] if open_cash else None

                # Número visível da venda. O ID interno nunca é reutilizado.
                # Se todas as vendas forem excluídas, a próxima começa novamente em #1.
                # Número visível: sequência das vendas que realmente existem.
                # O ID interno do banco continua independente e nunca é reutilizado.
                current_sales_count = conn.execute(
                    "SELECT COUNT(*) AS n FROM sales WHERE status <> 'CANCELLED'"
                ).fetchone()["n"]
                sale_number = int(current_sales_count or 0) + 1

                sale_token = (request.form.get("sale_token") or session.get("sale_form_token") or "").strip()
                if not sale_token:
                    sale_token = secrets.token_urlsafe(24)

                if conn.postgres:
                    cur = conn.execute(
                        """INSERT INTO sales (total, subtotal, discount_percent, customer_id, payment_method, username, created_at, cash_session_id, sale_number, sale_token, status)
                           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'COMPLETED') RETURNING id""",
                        (total, subtotal_total, discount_percent, customer_id, payment_method, username, now, cash_session_id, sale_number, sale_token)
                    )
                    sale_id = cur.fetchone()["id"]
                else:
                    cur = conn.execute(
                        """INSERT INTO sales (total, subtotal, discount_percent, customer_id, payment_method, username, created_at, cash_session_id, sale_number, sale_token, status)
                           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'COMPLETED')""",
                        (total, subtotal_total, discount_percent, customer_id, payment_method, username, now, cash_session_id, sale_number, sale_token)
                    )
                    sale_id = cur.lastrowid

                for product, quantity, unit_price, item_subtotal in checked:
                    conn.execute(
                        """INSERT INTO sale_items (sale_id, product_id, quantity, unit_price, unit_cost, subtotal)
                           VALUES (?, ?, ?, ?, ?, ?)""",
                        (sale_id, product["id"], quantity, unit_price, float(product.get("cost",0) if hasattr(product, "get") else product["cost"] or 0), item_subtotal)
                    )
                    conn.execute("UPDATE products SET stock = ? WHERE id = ?", (product["stock"] - quantity, product["id"]))
                    conn.execute(
                        """INSERT INTO movements (product_id, type, quantity, note, created_at)
                           VALUES (?, ?, ?, ?, ?)""",
                        (product["id"], "SAIDA", quantity, f"Venda #{sale_number}", now)
                    )

                conn.commit()
                audit("NOVA VENDA", f"Venda #{sale_number} - Subtotal R$ {subtotal_total:.2f} - Desconto {discount_percent:.2f}% - Total R$ {total:.2f}")
                session.pop("sale_cart", None)
                session.pop("sale_form_token", None)
                flash(f"Venda #{sale_number} finalizada com sucesso.", "success")
                return redirect(url_for("sale_detail", sale_id=sale_id))
            except Exception as exc:
                conn.rollback()
                # Protege contra duplo clique/reenvio: o mesmo token de venda só pode ser processado uma vez.
                try:
                    existing = conn.execute("SELECT id, sale_number FROM sales WHERE sale_token = ? LIMIT 1", (sale_token,)).fetchone()
                except Exception:
                    existing = None
                if existing:
                    session.pop("sale_form_token", None)
                    flash(f"Venda #{existing['sale_number'] or existing['id']} já foi finalizada. O segundo clique foi ignorado.", "info")
                    return redirect(url_for("sale_detail", sale_id=existing["id"]))
                flash(str(exc), "danger")
                return redirect(url_for("new_sale"))
            finally:
                conn.close()

    conn = db()
    products = conn.execute("SELECT * FROM products WHERE stock > 0 ORDER BY name, brand, color, size").fetchall()
    customers = conn.execute("SELECT * FROM customers ORDER BY name").fetchall()
    open_cash = conn.execute("SELECT * FROM cash_sessions WHERE status='OPEN' ORDER BY id DESC LIMIT 1").fetchone()
    conn.close()
    subtotal = sum(i["quantity"] * i["unit_price"] for i in cart)
    if not session.get("sale_form_token"):
        session["sale_form_token"] = secrets.token_urlsafe(24)
    return render_template("new_sale.html", products=products, customers=customers, cart=cart, total=subtotal, subtotal=subtotal, open_cash=open_cash, sale_form_token=session["sale_form_token"])


@app.route("/sales/<int:sale_id>")
@login_required
def sale_detail(sale_id):
    """Exibe uma venda de forma compatível com bancos antigos e novos.

    Se uma instalação antiga ainda não tiver alguma coluna opcional de clientes/desconto,
    a venda continua sendo aberta usando os dados básicos, em vez de gerar HTTP 500.
    """
    conn = db()
    try:
        try:
            sale = conn.execute("""
                SELECT s.*,
                       COALESCE(c.name, '') AS customer_name,
                       COALESCE(c.cpf, '') AS customer_cpf,
                       COALESCE(c.phone, '') AS customer_phone
                FROM sales s
                LEFT JOIN customers c ON c.id = s.customer_id
                WHERE s.id = ?
            """, (sale_id,)).fetchone()
        except Exception:
            conn.rollback()
            sale = conn.execute("""
                SELECT s.*, '' AS customer_name, '' AS customer_cpf, '' AS customer_phone
                FROM sales s WHERE s.id = ?
            """, (sale_id,)).fetchone()

        if not sale:
            return "Venda não encontrada", 404

        items = conn.execute("""
            SELECT si.*, p.name, p.category, p.brand, p.color, p.size
            FROM sale_items si
            LEFT JOIN products p ON p.id = si.product_id
            WHERE si.sale_id = ?
            ORDER BY si.id
        """, (sale_id,)).fetchall()

        # Normaliza campos opcionais para o template.
        sale_data = dict(sale)
        # Número exibido é baseado na posição atual da venda entre as vendas existentes.
        # Isso evita mostrar o ID interno (ex.: /sales/14) como "Venda #14".
        display_row = conn.execute(
            "SELECT COUNT(*) AS n FROM sales WHERE id <= ? AND status <> 'CANCELLED' ", (sale_id,)
        ).fetchone()
        sale_data["display_number"] = int(sale_data.get("sale_number") or (display_row["n"] if display_row else 1) or 1)
        sale_data.setdefault("subtotal", sale_data.get("total", 0) or 0)
        sale_data.setdefault("discount_percent", 0)
        sale_data.setdefault("customer_name", "")
        sale_data.setdefault("customer_cpf", "")
        sale_data.setdefault("customer_phone", "")

        item_data = []
        for item in items:
            d = dict(item)
            d.setdefault("name", "Produto removido")
            d.setdefault("brand", "")
            d.setdefault("color", "")
            d.setdefault("size", "")
            d.setdefault("unit_price", 0)
            d.setdefault("subtotal", 0)
            item_data.append(d)

        return render_template("sale_detail.html", sale=sale_data, items=item_data)
    except Exception as exc:
        conn.rollback()
        app.logger.exception("Erro ao abrir venda #%s", sale_id)
        flash("Não foi possível abrir os detalhes desta venda. A venda permanece registrada.", "danger")
        return redirect(url_for("sales"))
    finally:
        conn.close()


@app.route("/customers")
@login_required
def customers():
    q = request.args.get("q", "").strip()
    conn = db()
    if q:
        like = f"%{q}%"
        rows = conn.execute("""SELECT * FROM customers
                              WHERE name LIKE ? OR COALESCE(cpf,'') LIKE ? OR COALESCE(phone,'') LIKE ?
                              ORDER BY name""", (like, like, like)).fetchall()
    else:
        rows = conn.execute("SELECT * FROM customers ORDER BY name").fetchall()
    conn.close()
    return render_template("customers.html", customers=rows, q=q)


@app.route("/customers/new", methods=["GET", "POST"])
@login_required
def new_customer():
    return_to = request.values.get("return_to", "")
    if request.method == "POST":
        name = request.form.get("name", "").strip()
        cpf = request.form.get("cpf", "").strip()
        phone = request.form.get("phone", "").strip()
        whatsapp = request.form.get("whatsapp", "").strip()
        address = request.form.get("address", "").strip()
        if not name:
            flash("Informe o nome do cliente.", "danger")
            return render_template("customer_form.html", customer=None, return_to=return_to)
        conn = db()
        now = datetime.now(TZ).strftime("%Y-%m-%d %H:%M:%S")
        try:
            if conn.postgres:
                cur = conn.execute("""INSERT INTO customers (name, cpf, phone, whatsapp, address, created_at)
                                      VALUES (?, ?, ?, ?, ?, ?) RETURNING id""",
                                   (name, cpf, phone, whatsapp, address, now))
                customer_id = cur.fetchone()["id"]
            else:
                cur = conn.execute("""INSERT INTO customers (name, cpf, phone, whatsapp, address, created_at)
                                      VALUES (?, ?, ?, ?, ?, ?)""",
                                   (name, cpf, phone, whatsapp, address, now))
                customer_id = cur.lastrowid
            conn.commit()
        except Exception:
            conn.rollback()
            app.logger.exception("Erro ao cadastrar cliente")
            flash("Não foi possível cadastrar o cliente. Verifique os dados e tente novamente.", "danger")
            conn.close()
            return render_template("customer_form.html", customer=None, return_to=return_to)
        conn.close()
        audit("CRIAÇÃO DE CLIENTE", f"Cliente #{customer_id} - {name}")
        flash("Cliente cadastrado com sucesso.", "success")
        if return_to == "sale":
            return redirect(url_for("new_sale"))
        return redirect(url_for("customers"))
    return render_template("customer_form.html", customer=None, return_to=return_to)


@app.route("/customers/<int:customer_id>/edit", methods=["GET", "POST"])
@login_required
def edit_customer(customer_id):
    conn = db()
    customer = conn.execute("SELECT * FROM customers WHERE id = ?", (customer_id,)).fetchone()
    if not customer:
        conn.close(); return "Cliente não encontrado", 404
    if request.method == "POST":
        values = (request.form.get("name", "").strip(), request.form.get("cpf", "").strip(),
                  request.form.get("phone", "").strip(), request.form.get("whatsapp", "").strip(),
                  request.form.get("address", "").strip(), customer_id)
        if not values[0]:
            conn.close(); flash("Informe o nome do cliente.", "danger")
            return render_template("customer_form.html", customer=customer)
        conn.execute("""UPDATE customers SET name=?, cpf=?, phone=?, whatsapp=?, address=? WHERE id=?""", values)
        conn.commit(); conn.close()
        audit("ALTERAÇÃO DE CLIENTE", f"Cliente #{customer_id} - {values[0]}")
        flash("Cliente atualizado com sucesso.", "success")
        return redirect(url_for("customers"))
    conn.close()
    return render_template("customer_form.html", customer=customer)


@app.post("/customers/<int:customer_id>/delete")
@login_required
@admin_required
def delete_customer(customer_id):
    conn = db()
    customer = conn.execute("SELECT * FROM customers WHERE id = ?", (customer_id,)).fetchone()
    if not customer:
        conn.close(); flash("Cliente não encontrado.", "danger"); return redirect(url_for("customers"))
    linked = conn.execute("SELECT COUNT(*) AS c FROM sales WHERE customer_id = ?", (customer_id,)).fetchone()["c"]
    if int(linked or 0) > 0:
        conn.close(); flash("Não é possível excluir um cliente que possui vendas. O histórico foi preservado.", "warning"); return redirect(url_for("customers"))
    conn.execute("DELETE FROM customers WHERE id = ?", (customer_id,)); conn.commit(); conn.close()
    audit("EXCLUSÃO DE CLIENTE", f"Cliente #{customer_id} - {customer['name']}")
    flash("Cliente excluído com sucesso.", "success")
    return redirect(url_for("customers"))



@app.route("/cash", methods=["GET", "POST"])
@login_required
def cash():
    conn = db()
    if request.method == "POST":
        action = request.form.get("action")
        now = datetime.now(TZ).strftime("%Y-%m-%d %H:%M:%S")
        username = get_current_user()["username"]

        if action == "open":
            try:
                opening = float(request.form.get("opening_amount") or 0)
            except (TypeError, ValueError):
                opening = -1
            if opening < 0:
                flash("Informe um valor inicial válido.", "danger")
            elif conn.execute("SELECT id FROM cash_sessions WHERE status='OPEN' LIMIT 1").fetchone():
                flash("Já existe um caixa aberto.", "warning")
            else:
                if conn.postgres:
                    cur = conn.execute("""
                        INSERT INTO cash_sessions (opening_amount, opened_by, opened_at, status)
                        VALUES (?, ?, ?, 'OPEN') RETURNING id
                    """, (opening, username, now))
                    cash_id = cur.fetchone()["id"]
                else:
                    cur = conn.execute("""
                        INSERT INTO cash_sessions (opening_amount, opened_by, opened_at, status)
                        VALUES (?, ?, ?, 'OPEN')
                    """, (opening, username, now))
                    cash_id = cur.lastrowid
                conn.commit()
                audit("ABERTURA DE CAIXA", f"Caixa #{cash_id} aberto com R$ {opening:.2f}")
                flash("Caixa aberto com sucesso.", "success")

        elif action == "close":
            row = conn.execute("SELECT * FROM cash_sessions WHERE status='OPEN' ORDER BY id DESC LIMIT 1").fetchone()
            if not row:
                flash("Não existe caixa aberto.", "warning")
            else:
                try:
                    closing = float(request.form.get("closing_amount") or 0)
                except (TypeError, ValueError):
                    closing = -1
                if closing < 0:
                    flash("Informe um valor final válido.", "danger")
                else:
                    cash_sales = conn.execute("""
                        SELECT COALESCE(SUM(total),0) total
                        FROM sales
                        WHERE cash_session_id=? AND payment_method='Dinheiro'
                    """, (row["id"],)).fetchone()["total"]
                    expected = float(row["opening_amount"] or 0) + float(cash_sales or 0)
                    difference = closing - expected
                    conn.execute("""
                        UPDATE cash_sessions
                        SET closing_amount=?, expected_amount=?, difference=?,
                            closed_by=?, closed_at=?, status='CLOSED'
                        WHERE id=?
                    """, (closing, expected, difference, username, now, row["id"]))
                    conn.commit()
                    audit("FECHAMENTO DE CAIXA", f"Caixa #{row['id']} - Esperado R$ {expected:.2f} - Informado R$ {closing:.2f} - Diferença R$ {difference:.2f}")
                    flash(f"Caixa fechado. Diferença: R$ {difference:.2f}.", "success")

        return redirect(url_for("cash"))

    current = conn.execute("SELECT * FROM cash_sessions WHERE status='OPEN' ORDER BY id DESC LIMIT 1").fetchone()
    history = conn.execute("SELECT * FROM cash_sessions ORDER BY id DESC LIMIT 20").fetchall()
    if current:
        cash_sales = conn.execute("""
            SELECT payment_method, COUNT(*) sales_count, COALESCE(SUM(total),0) total
            FROM sales WHERE cash_session_id=? AND status <> 'CANCELLED' GROUP BY payment_method ORDER BY total DESC
        """, (current["id"],)).fetchall()
        cash_total = conn.execute("""
            SELECT COALESCE(SUM(total),0) total FROM sales
            WHERE cash_session_id=? AND payment_method='Dinheiro' AND status <> 'CANCELLED'
        """, (current["id"],)).fetchone()["total"]
        cm = conn.execute("SELECT COALESCE(SUM(CASE WHEN type='SUPRIMENTO' THEN amount ELSE 0 END),0) supplies, COALESCE(SUM(CASE WHEN type IN ('SANGRIA','DESPESA') THEN amount ELSE 0 END),0) withdrawals FROM cash_movements WHERE cash_session_id=?", (current["id"],)).fetchone()
        expected_cash = float(current["opening_amount"] or 0) + float(cash_total or 0) + float(cm["supplies"] or 0) - float(cm["withdrawals"] or 0)
    else:
        cash_sales=[]; expected_cash=0
    cash_moves = conn.execute("SELECT * FROM cash_movements WHERE cash_session_id = ? ORDER BY id DESC LIMIT 50", (current["id"],)).fetchall() if current else []
    conn.close()
    return render_template("cash.html", current=current, history=history, cash_sales=cash_sales, expected_cash=expected_cash, cash_moves=cash_moves)


@app.route("/admin/backup")
@login_required
@admin_required
def admin_backup():
    import csv, io, zipfile
    tables = ["users","products","movements","sales","sale_items","customers","suppliers","cash_sessions","cash_movements","returns","return_items","categories","audit_logs"]
    mem = io.BytesIO()
    with zipfile.ZipFile(mem, "w", zipfile.ZIP_DEFLATED) as z:
        conn = db()
        for table in tables:
            try:
                rows = conn.execute(f"SELECT * FROM {table} ORDER BY 1").fetchall()
            except Exception:
                continue
            output = io.StringIO()
            writer = csv.writer(output)
            if rows:
                keys = list(rows[0].keys()) if hasattr(rows[0], "keys") else []
                if table == "users" and "password" in keys:
                    keys.remove("password")
                writer.writerow(keys)
                for row in rows:
                    values = [row[k] for k in keys] if hasattr(row, "__getitem__") and hasattr(row, "keys") else list(row)
                    writer.writerow(values)
            else:
                # Cabeçalho conhecido não é essencial; tabela vazia fica identificada.
                writer.writerow(["sem_registros"])
            z.writestr(f"{table}.csv", output.getvalue())
        conn.close()
    mem.seek(0)
    audit("BACKUP", "Backup administrativo exportado em CSV/ZIP")
    return send_file(mem, as_attachment=True,
                     download_name=f"backup_pyetro_{datetime.now(TZ).strftime('%Y%m%d_%H%M%S')}.zip",
                     mimetype="application/zip")


@app.route("/reports", methods=["GET"])
@login_required
def reports():
    now = datetime.now(TZ)
    mode = request.args.get("mode", "month")
    selected_date = request.args.get("date", now.strftime("%Y-%m-%d"))
    try:
        datetime.strptime(selected_date, "%Y-%m-%d")
    except ValueError:
        selected_date = now.strftime("%Y-%m-%d")

    try:
        month = int(request.args.get("month") or now.month)
        year = int(request.args.get("year") or now.year)
    except ValueError:
        month, year = now.month, now.year
    if not 1 <= month <= 12: month = now.month
    if not 2000 <= year <= 2100: year = now.year

    period = f"{year:04d}-{month:02d}"
    conn = db()

    # Resumo do mês selecionado.
    summary = conn.execute("""
        SELECT COUNT(*) AS sales_count, COALESCE(SUM(total), 0) AS revenue,
               COALESCE(SUM(subtotal), 0) AS subtotal,
               COALESCE(SUM(COALESCE(subtotal, total) * COALESCE(discount_percent, 0) / 100.0), 0) AS discount
        FROM sales WHERE status <> 'CANCELLED' AND substr(created_at, 1, 7) = ?
    """, (period,)).fetchone()
    items = conn.execute("""
        SELECT COALESCE(SUM(quantity), 0) AS items_sold
        FROM sale_items si JOIN sales s ON s.id = si.sale_id
        WHERE s.status <> 'CANCELLED' AND substr(s.created_at, 1, 7) = ?
    """, (period,)).fetchone()
    payments = conn.execute("""
        SELECT payment_method, COUNT(*) AS sales_count, COALESCE(SUM(total), 0) AS total
        FROM sales WHERE status <> 'CANCELLED' AND substr(created_at, 1, 7) = ?
        GROUP BY payment_method ORDER BY total DESC
    """, (period,)).fetchall()
    top_products = conn.execute("""
        SELECT p.name, COALESCE(p.brand,'') brand, COALESCE(p.color,'') color,
               COALESCE(p.size,'') size, SUM(si.quantity) quantity,
               SUM(si.subtotal) total
        FROM sale_items si JOIN sales s ON s.id = si.sale_id
        JOIN products p ON p.id = si.product_id
        WHERE s.status <> 'CANCELLED' AND substr(s.created_at, 1, 7) = ?
        GROUP BY p.id, p.name, p.brand, p.color, p.size
        ORDER BY quantity DESC, total DESC LIMIT 10
    """, (period,)).fetchall()
    monthly = conn.execute("""
        SELECT substr(created_at,1,7) period, COUNT(*) sales_count,
               COALESCE(SUM(total),0) total
        FROM sales WHERE status <> 'CANCELLED' AND substr(created_at,1,4) = ?
        GROUP BY substr(created_at,1,7) ORDER BY period
    """, (str(year),)).fetchall()

    # Resumo e lista do dia selecionado.
    day_summary = conn.execute("""
        SELECT COUNT(*) AS sales_count, COALESCE(SUM(total),0) revenue,
               COALESCE(SUM(subtotal),0) subtotal,
               COALESCE(SUM(COALESCE(subtotal, total) * COALESCE(discount_percent, 0) / 100.0),0) discount
        FROM sales WHERE status <> 'CANCELLED' AND substr(created_at,1,10) = ?
    """, (selected_date,)).fetchone()
    day_items = conn.execute("""
        SELECT COALESCE(SUM(si.quantity),0) items_sold
        FROM sale_items si JOIN sales s ON s.id = si.sale_id
        WHERE s.status <> 'CANCELLED' AND substr(s.created_at,1,10) = ?
    """, (selected_date,)).fetchone()
    day_payments = conn.execute("""
        SELECT payment_method, COUNT(*) sales_count, COALESCE(SUM(total),0) total
        FROM sales WHERE status <> 'CANCELLED' AND substr(created_at,1,10) = ?
        GROUP BY payment_method ORDER BY total DESC
    """, (selected_date,)).fetchall()
    day_sales = conn.execute("""
        SELECT id, sale_number, created_at, username, payment_method, total,
               COALESCE(subtotal,total) subtotal, (COALESCE(subtotal,total) * COALESCE(discount_percent,0) / 100.0) discount
        FROM sales WHERE status <> 'CANCELLED' AND substr(created_at,1,10) = ?
        ORDER BY id DESC
    """, (selected_date,)).fetchall()
    profit_summary = conn.execute("""SELECT COALESCE(SUM(si.subtotal - (si.unit_cost * si.quantity)),0) profit FROM sales s JOIN sale_items si ON si.sale_id=s.id WHERE s.status <> 'CANCELLED' AND substr(s.created_at,1,7)=?""", (period,)).fetchone()
    day_profit = conn.execute("""SELECT COALESCE(SUM(si.subtotal - (si.unit_cost * si.quantity)),0) profit FROM sales s JOIN sale_items si ON si.sale_id=s.id WHERE s.status <> 'CANCELLED' AND substr(s.created_at,1,10)=?""", (selected_date,)).fetchone()
    conn.close()

    revenue = float(summary["revenue"] or 0); sales_count = int(summary["sales_count"] or 0)
    items_sold = int(items["items_sold"] or 0); ticket_average = revenue / sales_count if sales_count else 0
    day_revenue = float(day_summary["revenue"] or 0); day_sales_count = int(day_summary["sales_count"] or 0)
    day_items_sold = int(day_items["items_sold"] or 0); day_ticket_average = day_revenue / day_sales_count if day_sales_count else 0
    day_subtotal = float(day_summary["subtotal"] or 0); day_discount = float(day_summary["discount"] or 0)
    profit = float(profit_summary["profit"] or 0); day_profit_value = float(day_profit["profit"] or 0)

    months = [(1,"Janeiro"),(2,"Fevereiro"),(3,"Março"),(4,"Abril"),(5,"Maio"),(6,"Junho"),
              (7,"Julho"),(8,"Agosto"),(9,"Setembro"),(10,"Outubro"),(11,"Novembro"),(12,"Dezembro")]
    years = list(range(now.year - 5, now.year + 1))
    return render_template("reports.html", month=month, year=year, months=months, years=years,
        mode=mode, selected_date=selected_date, revenue=revenue, sales_count=sales_count,
        items_sold=items_sold, ticket_average=ticket_average, payments=payments,
        top_products=top_products, monthly=monthly, day_revenue=day_revenue,
        day_sales_count=day_sales_count, day_items_sold=day_items_sold,
        day_ticket_average=day_ticket_average, day_subtotal=day_subtotal,
        day_discount=day_discount, day_payments=day_payments, day_sales=day_sales, profit=profit, day_profit=day_profit_value)


@app.route("/admin/users")
@login_required
@admin_required
def admin_users():
    conn = db()
    users = conn.execute(
        """SELECT id, username, role, active
           FROM users
           ORDER BY CASE WHEN LOWER(username) = 'admin' THEN 0 ELSE 1 END, username"""
    ).fetchall()
    conn.close()
    return render_template("users.html", users=users)


@app.route("/admin/users/new", methods=["GET", "POST"])
@login_required
@admin_required
def admin_new_user():
    if request.method == "POST":
        username = request.form.get("username", "").strip()
        password = request.form.get("password", "")
        role = request.form.get("role", "operator")

        if not username or not password:
            flash("Informe usuário e senha.", "danger")
            return render_template("user_form.html", user=None)

        if role not in {"admin", "operator"}:
            role = "operator"

        conn = db()
        exists = conn.execute(
            "SELECT id FROM users WHERE LOWER(username) = LOWER(?)",
            (username,)
        ).fetchone()

        if exists:
            conn.close()
            flash("Esse usuário já existe.", "warning")
            return render_template("user_form.html", user=None)

        conn.execute(
            "INSERT INTO users (username, password, role, active) VALUES (?, ?, ?, ?)",
            (username, generate_password_hash(password), role, True)
        )
        conn.commit()
        conn.close()

        audit("CRIAÇÃO DE USUÁRIO", f"Usuário {username} criado como {role}")
        flash("Usuário criado com sucesso.", "success")
        return redirect(url_for("admin_users"))

    return render_template("user_form.html", user=None)


@app.route("/admin/users/<int:user_id>/edit", methods=["GET", "POST"])
@login_required
@admin_required
def admin_edit_user(user_id):
    conn = db()
    user = conn.execute(
        "SELECT id, username, role, active FROM users WHERE id = ?",
        (user_id,)
    ).fetchone()

    if not user:
        conn.close()
        return "Usuário não encontrado", 404

    protected = user["username"].lower() == "admin"

    if request.method == "POST":
        role = request.form.get("role", "operator")
        password = request.form.get("password", "")

        if protected:
            role = "admin"

        if role not in {"admin", "operator"}:
            role = "operator"

        if password:
            conn.execute(
                "UPDATE users SET role = ?, password = ? WHERE id = ?",
                (role, generate_password_hash(password), user_id)
            )
        else:
            conn.execute(
                "UPDATE users SET role = ? WHERE id = ?",
                (role, user_id)
            )

        conn.commit()
        conn.close()

        audit(
            "ALTERAÇÃO DE USUÁRIO",
            f"Usuário {user['username']} - perfil {role}" +
            (" - senha alterada" if password else "")
        )
        flash("Usuário atualizado com sucesso.", "success")
        return redirect(url_for("admin_users"))

    conn.close()
    return render_template("user_form.html", user=user)


@app.post("/admin/users/<int:user_id>/toggle")
@login_required
@admin_required
def admin_toggle_user(user_id):
    conn = db()
    user = conn.execute(
        "SELECT id, username, role, active FROM users WHERE id = ?",
        (user_id,)
    ).fetchone()

    if not user:
        conn.close()
        flash("Usuário não encontrado.", "danger")
        return redirect(url_for("admin_users"))

    # Proteção absoluta da conta principal.
    if user["username"].lower() == "admin":
        conn.close()
        flash("A conta admin principal não pode ser desativada.", "warning")
        return redirect(url_for("admin_users"))

    # Não permite desativar o próprio usuário logado.
    if get_current_user() and int(user["id"]) == int(get_current_user()["id"]):
        conn.close()
        flash("Você não pode desativar o próprio usuário.", "warning")
        return redirect(url_for("admin_users"))

    new_active = not bool(user["active"])

    # Nunca deixa o sistema ficar sem administrador ativo.
    if new_active == 0 and user["role"] == "admin":
        active_admins = conn.execute(
            "SELECT COUNT(*) AS c FROM users WHERE role = 'admin' AND active = ?",
            (True,)
        ).fetchone()["c"]
        if int(active_admins or 0) <= 1:
            conn.close()
            flash("Não é possível desativar o último administrador ativo.", "warning")
            return redirect(url_for("admin_users"))

    conn.execute(
        "UPDATE users SET active = ? WHERE id = ?",
        (new_active, user_id)
    )
    conn.commit()
    conn.close()

    audit(
        "STATUS DE USUÁRIO",
        f"Usuário {user['username']} -> {'ativo' if new_active else 'desativado'}"
    )
    flash(
        f"Usuário {'ativado' if new_active else 'desativado'} com sucesso.",
        "success"
    )
    return redirect(url_for("admin_users"))


@app.post("/admin/users/<int:user_id>/delete")
@login_required
@admin_required
def admin_delete_user(user_id):
    conn = db()
    user = conn.execute(
        "SELECT id, username, role FROM users WHERE id = ?",
        (user_id,)
    ).fetchone()

    if not user:
        conn.close()
        flash("Usuário não encontrado.", "danger")
        return redirect(url_for("admin_users"))

    # Conta admin principal: não pode ser excluída.
    if user["username"].lower() == "admin":
        conn.close()
        flash("A conta admin principal não pode ser excluída.", "warning")
        return redirect(url_for("admin_users"))

    # Segurança adicional: não exclui o próprio usuário nem o último admin.
    if get_current_user() and int(user["id"]) == int(get_current_user()["id"]):
        conn.close()
        flash("Você não pode excluir o próprio usuário.", "warning")
        return redirect(url_for("admin_users"))

    if user["role"] == "admin":
        active_admins = conn.execute(
            "SELECT COUNT(*) AS c FROM users WHERE role = 'admin' AND active = ?",
            (True,)
        ).fetchone()["c"]
        if int(active_admins or 0) <= 1:
            conn.close()
            flash("Não é possível excluir o último administrador ativo.", "warning")
            return redirect(url_for("admin_users"))

    conn.execute("DELETE FROM users WHERE id = ?", (user_id,))
    conn.commit()
    conn.close()

    audit("EXCLUSÃO DE USUÁRIO", f"Usuário {user['username']}")
    flash("Usuário excluído com sucesso.", "success")
    return redirect(url_for("admin_users"))


@app.route("/admin/audit")
@login_required
@admin_required
def admin_audit():
    conn = db()
    logs = conn.execute(
        """SELECT * FROM audit_logs
           ORDER BY id DESC LIMIT 300"""
    ).fetchall()
    conn.close()
    return render_template("audit.html", logs=logs)


@app.post("/sales/<int:sale_id>/delete")
@login_required
@admin_required
def delete_sale(sale_id):
    conn = db()
    try:
        sale = conn.execute(
            "SELECT * FROM sales WHERE id = ?",
            (sale_id,)
        ).fetchone()

        if not sale:
            flash("Venda não encontrada.", "danger")
            return redirect(url_for("sales"))

        if int(conn.execute("SELECT COUNT(*) c FROM returns WHERE sale_id=?",(sale_id,)).fetchone()["c"] or 0) > 0:
            flash("Não é possível excluir uma venda com troca/devolução registrada. Preserve o histórico.", "warning")
            return redirect(url_for("sales"))
        display_sale_number = int(dict(sale).get("sale_number") or sale_id)

        items = conn.execute(
            "SELECT * FROM sale_items WHERE sale_id = ?",
            (sale_id,)
        ).fetchall()

        # Reverte o estoque dos itens vendidos.
        for item in items:
            product = conn.execute(
                "SELECT id, stock FROM products WHERE id = ?",
                (item["product_id"],)
            ).fetchone()

            if product:
                conn.execute(
                    "UPDATE products SET stock = ? WHERE id = ?",
                    (product["stock"] + item["quantity"], product["id"])
                )

            conn.execute(
                """DELETE FROM movements
                   WHERE product_id = ? AND type = 'SAIDA'
                     AND note = ?""",
                (item["product_id"], f"Venda #{display_sale_number}")
            )

        conn.execute("DELETE FROM sale_items WHERE sale_id = ?", (sale_id,))
        conn.execute("DELETE FROM sales WHERE id = ?", (sale_id,))
        conn.commit()

        audit(
            "EXCLUSÃO DE VENDA",
            f"Venda #{display_sale_number} - estoque dos itens restaurado"
        )
        flash(f"Venda #{display_sale_number} excluída e estoque restaurado.", "success")

    except Exception as exc:
        conn.rollback()
        flash(f"Não foi possível excluir a venda: {exc}", "danger")
    finally:
        conn.close()

    return redirect(url_for("sales"))



@app.route("/suppliers")
@login_required
@admin_required
def suppliers():
    q=request.args.get("q","").strip(); conn=db()
    if q:
        like=f"%{q}%"; rows=conn.execute("SELECT * FROM suppliers WHERE name LIKE ? OR COALESCE(cnpj,'') LIKE ? OR COALESCE(phone,'') LIKE ? ORDER BY name",(like,like,like)).fetchall()
    else: rows=conn.execute("SELECT * FROM suppliers ORDER BY name").fetchall()
    conn.close(); return render_template("suppliers.html", suppliers=rows, q=q)

@app.route("/suppliers/new", methods=["GET","POST"])
@login_required
@admin_required
def new_supplier():
    if request.method=="POST":
        vals=(request.form.get("name","").strip(),request.form.get("cnpj","").strip(),request.form.get("phone","").strip(),request.form.get("whatsapp","").strip(),request.form.get("email","").strip(),request.form.get("address","").strip(),datetime.now(TZ).strftime("%Y-%m-%d %H:%M:%S"))
        if not vals[0]: flash("Informe o nome do fornecedor.","danger"); return render_template("supplier_form.html", supplier=None)
        conn=db()
        try:
            conn.execute("INSERT INTO suppliers (name,cnpj,phone,whatsapp,email,address,created_at) VALUES (?,?,?,?,?,?,?)",vals); conn.commit(); flash("Fornecedor cadastrado.","success")
        except Exception as exc: conn.rollback(); flash(f"Não foi possível cadastrar: {exc}","danger")
        finally: conn.close()
        return redirect(url_for("suppliers"))
    return render_template("supplier_form.html", supplier=None)

@app.route("/suppliers/<int:supplier_id>/edit", methods=["GET","POST"])
@login_required
@admin_required
def edit_supplier(supplier_id):
    conn=db(); supplier=conn.execute("SELECT * FROM suppliers WHERE id=?",(supplier_id,)).fetchone()
    if not supplier: conn.close(); return "Fornecedor não encontrado",404
    if request.method=="POST":
        vals=(request.form.get("name","").strip(),request.form.get("cnpj","").strip(),request.form.get("phone","").strip(),request.form.get("whatsapp","").strip(),request.form.get("email","").strip(),request.form.get("address","").strip(),supplier_id)
        conn.execute("UPDATE suppliers SET name=?,cnpj=?,phone=?,whatsapp=?,email=?,address=? WHERE id=?",vals); conn.commit(); conn.close(); flash("Fornecedor atualizado.","success"); return redirect(url_for("suppliers"))
    conn.close(); return render_template("supplier_form.html", supplier=supplier)

@app.post("/suppliers/<int:supplier_id>/delete")
@login_required
@admin_required
def delete_supplier(supplier_id):
    conn=db(); linked=conn.execute("SELECT COUNT(*) c FROM products WHERE supplier_id=?",(supplier_id,)).fetchone()["c"]
    if linked: conn.close(); flash("Fornecedor vinculado a produtos não pode ser excluído.","warning"); return redirect(url_for("suppliers"))
    conn.execute("DELETE FROM suppliers WHERE id=?",(supplier_id,)); conn.commit(); conn.close(); flash("Fornecedor excluído.","success"); return redirect(url_for("suppliers"))

@app.route("/customers/<int:customer_id>/history")
@login_required
def customer_history(customer_id):
    conn=db(); customer=conn.execute("SELECT * FROM customers WHERE id=?",(customer_id,)).fetchone()
    if not customer: conn.close(); return "Cliente não encontrado",404
    sales_rows=conn.execute("SELECT * FROM sales WHERE customer_id=? ORDER BY id DESC",(customer_id,)).fetchall(); conn.close()
    return render_template("customer_history.html",customer=customer,sales=sales_rows)

@app.route("/stock/adjust/<int:product_id>",methods=["GET","POST"])
@login_required
@admin_required
def adjust_stock(product_id):
    conn=db(); product=conn.execute("SELECT * FROM products WHERE id=?",(product_id,)).fetchone()
    if not product: conn.close(); return "Produto não encontrado",404
    if request.method=="POST":
        target=int(request.form.get("target_stock") or 0); note=request.form.get("note","").strip() or "Ajuste de inventário"
        if target<0: flash("Estoque não pode ser negativo.","danger")
        else:
            delta=target-int(product["stock"] or 0); typ="AJUSTE"; now=datetime.now(TZ).strftime("%Y-%m-%d %H:%M:%S")
            conn.execute("UPDATE products SET stock=? WHERE id=?",(target,product_id)); conn.execute("INSERT INTO movements (product_id,type,quantity,note,created_at) VALUES (?,?,?,?,?)",(product_id,typ,delta,note,now)); conn.commit(); conn.close(); audit("AJUSTE DE ESTOQUE",f"Produto #{product_id}: {product['stock']} -> {target}"); flash("Inventário ajustado com sucesso.","success"); return redirect(url_for("products"))
    conn.close(); return render_template("stock_adjust.html",product=product)

@app.post("/cash/movement")
@login_required
def cash_movement():
    conn=db(); current=conn.execute("SELECT * FROM cash_sessions WHERE status='OPEN' ORDER BY id DESC LIMIT 1").fetchone()
    if not current: conn.close(); flash("Abra o caixa antes de registrar uma movimentação.","warning"); return redirect(url_for("cash"))
    typ=request.form.get("type"); amount=parse_money(request.form.get("amount")); desc=request.form.get("description","").strip()
    if typ not in {"SANGRIA","SUPRIMENTO","DESPESA"} or amount<=0: conn.close(); flash("Informe tipo e valor válidos.","danger"); return redirect(url_for("cash"))
    now=datetime.now(TZ).strftime("%Y-%m-%d %H:%M:%S"); conn.execute("INSERT INTO cash_movements (cash_session_id,type,amount,description,username,created_at) VALUES (?,?,?,?,?,?)",(current["id"],typ,amount,desc,get_current_user()["username"],now)); conn.commit(); conn.close(); audit("MOVIMENTAÇÃO DE CAIXA",f"{typ} R$ {amount:.2f} - {desc}"); flash("Movimentação de caixa registrada.","success"); return redirect(url_for("cash"))

@app.route("/sales/<int:sale_id>/cancel",methods=["POST"])
@login_required
@admin_required
def cancel_sale(sale_id):
    conn=db(); sale=conn.execute("SELECT * FROM sales WHERE id=?",(sale_id,)).fetchone()
    if not sale: conn.close(); flash("Venda não encontrada.","danger"); return redirect(url_for("sales"))
    if dict(sale).get("status","COMPLETED")=="CANCELLED": conn.close(); flash("Venda já está cancelada.","warning"); return redirect(url_for("sales"))
    returned=conn.execute("SELECT COUNT(*) c FROM returns WHERE sale_id=?",(sale_id,)).fetchone()["c"]
    if int(returned or 0)>0: conn.close(); flash("Esta venda possui troca/devolução. Faça o acerto pelo histórico antes de cancelar.","warning"); return redirect(url_for("sales"))
    items=conn.execute("SELECT * FROM sale_items WHERE sale_id=?",(sale_id,)).fetchall(); now=datetime.now(TZ).strftime("%Y-%m-%d %H:%M:%S")
    for item in items:
        conn.execute("UPDATE products SET stock=stock+? WHERE id=?",(item["quantity"],item["product_id"]))
        conn.execute("INSERT INTO movements (product_id,type,quantity,note,created_at) VALUES (?,?,?,?,?)",(item["product_id"],"ENTRADA",item["quantity"],f"Cancelamento Venda #{dict(sale).get('sale_number') or sale_id}",now))
    conn.execute("UPDATE sales SET status='CANCELLED' WHERE id=?",(sale_id,))
    if sale["payment_method"] == "Dinheiro" and sale["cash_session_id"]:
        conn.execute("INSERT INTO cash_movements (cash_session_id,type,amount,description,username,created_at) VALUES (?,?,?,?,?,?)",(sale["cash_session_id"],"SANGRIA",float(sale["total"] or 0),f"Estorno cancelamento Venda #{dict(sale).get('sale_number') or sale_id}",get_current_user()["username"],now))
    conn.commit(); conn.close(); audit("CANCELAMENTO DE VENDA",f"Venda #{dict(sale).get('sale_number') or sale_id} cancelada e estoque restaurado"); flash("Venda cancelada e estoque restaurado. O histórico foi preservado.","success"); return redirect(url_for("sales"))

@app.route("/sales/<int:sale_id>/return",methods=["GET","POST"])
@login_required
@admin_required
def return_sale(sale_id):
    conn=db(); sale=conn.execute("SELECT * FROM sales WHERE id=?",(sale_id,)).fetchone()
    if not sale: conn.close(); return "Venda não encontrada",404
    items=conn.execute("SELECT si.*,p.name,p.stock FROM sale_items si JOIN products p ON p.id=si.product_id WHERE si.sale_id=?",(sale_id,)).fetchall()
    if request.method=="POST":
        try:
            sale_item_id=int(request.form.get("sale_item_id")); qty=int(request.form.get("quantity") or 0); replacement_id=int(request.form.get("replacement_product_id") or 0) or None; replacement_qty=int(request.form.get("replacement_quantity") or 0); typ=request.form.get("type","DEVOLUCAO")
            si=conn.execute("SELECT * FROM sale_items WHERE id=? AND sale_id=?",(sale_item_id,sale_id)).fetchone()
            already=conn.execute("SELECT COALESCE(SUM(quantity),0) q FROM return_items WHERE sale_item_id=?",(sale_item_id,)).fetchone()["q"]
            if not si or qty<=0 or qty>int(si["quantity"] or 0)-int(already or 0): raise ValueError("Quantidade de devolução inválida ou já devolvida.")
            if replacement_id and replacement_qty<=0: raise ValueError("Informe a quantidade da troca.")
            if replacement_id:
                rp=conn.execute("SELECT * FROM products WHERE id=?",(replacement_id,)).fetchone()
                if not rp or rp["stock"]<replacement_qty: raise ValueError("Estoque insuficiente para o produto de troca.")
            else: rp=None; replacement_qty=0
            original_value=float(si["unit_price"])*qty; replacement_value=float(rp["price"])*replacement_qty if rp else 0; difference=round(replacement_value-original_value,2)
            now=datetime.now(TZ).strftime("%Y-%m-%d %H:%M:%S"); user=get_current_user()["username"]
            cur=conn.execute("INSERT INTO returns (sale_id,type,reason,difference,username,created_at) VALUES (?,?,?,?,?,?)" + (" RETURNING id" if conn.postgres else ""),(sale_id,typ,request.form.get("reason","").strip(),difference,user,now)); rid=cur.fetchone()["id"] if conn.postgres else cur.lastrowid
            conn.execute("INSERT INTO return_items (return_id,sale_item_id,product_id,quantity,replacement_product_id,replacement_quantity) VALUES (?,?,?,?,?,?)",(rid,sale_item_id,si["product_id"],qty,replacement_id,replacement_qty))
            conn.execute("UPDATE products SET stock=stock+? WHERE id=?",(qty,si["product_id"]))
            conn.execute("INSERT INTO movements (product_id,type,quantity,note,created_at) VALUES (?,?,?,?,?)",(si["product_id"],"ENTRADA",qty,f"Devolução Venda #{dict(sale).get('sale_number') or sale_id}",now))
            if rp:
                conn.execute("UPDATE products SET stock=stock-? WHERE id=?",(replacement_qty,replacement_id)); conn.execute("INSERT INTO movements (product_id,type,quantity,note,created_at) VALUES (?,?,?,?,?)",(replacement_id,"SAIDA",replacement_qty,f"Troca Venda #{dict(sale).get('sale_number') or sale_id}",now))
            if difference < 0 and sale["payment_method"] == "Dinheiro" and sale["cash_session_id"]:
                conn.execute("INSERT INTO cash_movements (cash_session_id,type,amount,description,username,created_at) VALUES (?,?,?,?,?,?)",(sale["cash_session_id"],"SANGRIA",abs(difference),f"Reembolso devolução Venda #{dict(sale).get('sale_number') or sale_id}",user,now))
            elif difference > 0 and sale["cash_session_id"] and sale["payment_method"] == "Dinheiro":
                conn.execute("INSERT INTO cash_movements (cash_session_id,type,amount,description,username,created_at) VALUES (?,?,?,?,?,?)",(sale["cash_session_id"],"SUPRIMENTO",difference,f"Recebimento diferença troca Venda #{dict(sale).get('sale_number') or sale_id}",user,now))
            conn.commit(); conn.close(); audit("DEVOLUÇÃO/TROCA",f"Venda #{dict(sale).get('sale_number') or sale_id} - diferença R$ {difference:.2f}"); flash(f"Operação registrada. Diferença: R$ {difference:.2f}.","success"); return redirect(url_for("sale_detail",sale_id=sale_id))
        except Exception as exc: conn.rollback(); flash(str(exc),"danger")
    products=conn.execute("SELECT id,name,price,stock FROM products WHERE stock>0 ORDER BY name").fetchall(); conn.close(); return render_template("return_sale.html",sale=sale,items=items,products=products)

@app.route("/categories",methods=["GET","POST"])
@login_required
@admin_required
def categories():
    conn=db()
    if request.method=="POST":
        name=request.form.get("name","").strip()
        if name:
            try: conn.execute("INSERT INTO categories (name) VALUES (?)",(name,)); conn.commit(); flash("Categoria adicionada.","success")
            except Exception: conn.rollback(); flash("Categoria já existe ou é inválida.","warning")
    rows=conn.execute("SELECT * FROM categories ORDER BY name").fetchall(); conn.close(); return render_template("categories.html",categories=rows)

@app.post("/categories/<int:category_id>/delete")
@login_required
@admin_required
def delete_category(category_id):
    conn=db(); row=conn.execute("SELECT * FROM categories WHERE id=?",(category_id,)).fetchone();
    if row:
        linked=conn.execute("SELECT COUNT(*) c FROM products WHERE category=?",(row["name"],)).fetchone()["c"]
        if linked: conn.close(); flash("Categoria usada por produtos não pode ser excluída.","warning"); return redirect(url_for("categories"))
        conn.execute("DELETE FROM categories WHERE id=?",(category_id,)); conn.commit()
    conn.close(); return redirect(url_for("categories"))

@app.route("/reports/export.xlsx")
@login_required
def export_report_xlsx():
    from openpyxl import Workbook
    from openpyxl.styles import Font
    month=request.args.get("month",datetime.now(TZ).strftime("%m")); year=request.args.get("year",datetime.now(TZ).strftime("%Y")); period=f"{int(year):04d}-{int(month):02d}"
    conn=db(); rows=conn.execute("SELECT sale_number,created_at,username,payment_method,subtotal,discount_percent,total,status FROM sales WHERE status<>'CANCELLED' AND substr(created_at,1,7)=? ORDER BY id",(period,)).fetchall(); conn.close()
    wb=Workbook(); ws=wb.active; ws.title="Vendas"; headers=["Venda","Data","Usuário","Pagamento","Subtotal","Desconto %","Total","Status"]; ws.append(headers)
    for c in ws[1]: c.font=Font(bold=True)
    for r in rows: ws.append([r[k] for k in ["sale_number","created_at","username","payment_method","subtotal","discount_percent","total","status"]])
    for col in ["E","G"]:
        for cell in ws[col][1:]: cell.number_format="R$ #,##0.00"
    import io; mem=io.BytesIO(); wb.save(mem); mem.seek(0); return send_file(mem,as_attachment=True,download_name=f"vendas_{period}.xlsx",mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")

@app.route("/reports/export.csv")
@login_required
def export_report_csv():
    import csv, io
    month=request.args.get("month",datetime.now(TZ).strftime("%m")); year=request.args.get("year",datetime.now(TZ).strftime("%Y")); conn=db(); rows=conn.execute("SELECT sale_number,created_at,username,payment_method,subtotal,discount_percent,total,status FROM sales WHERE status<>'CANCELLED' AND substr(created_at,1,7)=? ORDER BY id",(f"{int(year):04d}-{int(month):02d}",)).fetchall(); conn.close(); out=io.StringIO(); w=csv.writer(out); w.writerow(["Venda","Data","Usuário","Pagamento","Subtotal","Desconto %","Total","Status"]); [w.writerow([r[k] for k in ["sale_number","created_at","username","payment_method","subtotal","discount_percent","total","status"]]) for r in rows]; mem=__import__('io').BytesIO(out.getvalue().encode('utf-8-sig')); return send_file(mem,as_attachment=True,download_name=f"vendas_{year}_{int(month):02d}.csv",mimetype="text/csv")

@app.route("/logo.jpg")
def logo():
    logo_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "static", "logo.jpg")
    if not os.path.isfile(logo_path):
        return "Logo não encontrado: " + logo_path, 404
    return send_file(logo_path, mimetype="image/jpeg")


if __name__ == "__main__":
    init_db()
    app.run(host="0.0.0.0", port=5000, debug=True)
